"""Modelli Pydantic L1/L2/L3 per E.Practice."""

from app.models.client import Client, ClientBase, ClientCreate, ClientStatus, ClientType, ClientUpdate
from app.models.activity_log import (
    ActivityAction,
    ActivityEntityType,
    ActivityLog,
    ActivityLogBase,
    ActivityLogCreate,
    ActivityLogUpdate,
    ActivityMetadata,
)
from app.models.attachment import (
    Attachment,
    AttachmentBase,
    AttachmentCreate,
    AttachmentSource,
    AttachmentUpdate,
)
from app.models.category import Category, CategoryBase, CategoryCreate, CategoryUpdate
from app.models.label import (
    ClientLabel,
    Label,
    LabelBase,
    LabelCreate,
    LabelUpdate,
    PracticeLabel,
)
from app.models.note import Note, NoteBase, NoteCreate, NoteUpdate
from app.models.phase_template import (
    PhaseTemplate,
    PhaseTemplateBase,
    PhaseTemplateCreate,
    PhaseTemplateUpdate,
)
from app.models.practice import (
    Practice,
    PracticeBase,
    PracticeCollaborator,
    PracticeCollaboratorBase,
    PracticeCollaboratorCreate,
    PracticeCollaboratorRole,
    PracticeCollaboratorUpdate,
    PracticeCreate,
    PracticePriority,
    PracticeStatus,
    PracticeUpdate,
)
from app.models.practice_event import (
    PracticeEvent,
    PracticeEventBase,
    PracticeEventCreate,
    PracticeEventType,
    PracticeEventUpdate,
    VisualPosition,
)
from app.models.practice_phase import (
    PracticePhase,
    PracticePhaseBase,
    PracticePhaseCreate,
    PracticePhaseStatus,
    PracticePhaseUpdate,
)
from app.models.reminder import Reminder, ReminderBase, ReminderCreate, ReminderStatus, ReminderUpdate
from app.models.requests import (
    AddLabelRequest,
    CompletePhaseRequest,
    CreateEventRequest,
    CreatePracticeRequest,
    CreatePracticeResponse,
    RemoveLabelRequest,
    SkipPhaseRequest,
    UpdatePhaseRequest,
)
from app.models.user import User, UserBase, UserCreate, UserRole, UserStatus, UserUpdate

__all__ = [
    "ActivityAction",
    "ActivityEntityType",
    "ActivityLog",
    "ActivityLogBase",
    "ActivityLogCreate",
    "ActivityLogUpdate",
    "ActivityMetadata",
    "AddLabelRequest",
    "Attachment",
    "AttachmentBase",
    "AttachmentCreate",
    "AttachmentSource",
    "AttachmentUpdate",
    "Category",
    "CategoryBase",
    "CategoryCreate",
    "CategoryUpdate",
    "Client",
    "ClientBase",
    "ClientCreate",
    "ClientLabel",
    "ClientStatus",
    "ClientType",
    "ClientUpdate",
    "CompletePhaseRequest",
    "CreateEventRequest",
    "CreatePracticeRequest",
    "CreatePracticeResponse",
    "Label",
    "LabelBase",
    "LabelCreate",
    "LabelUpdate",
    "Note",
    "NoteBase",
    "NoteCreate",
    "NoteUpdate",
    "PhaseTemplate",
    "PhaseTemplateBase",
    "PhaseTemplateCreate",
    "PhaseTemplateUpdate",
    "Practice",
    "PracticeBase",
    "PracticeCollaborator",
    "PracticeCollaboratorBase",
    "PracticeCollaboratorCreate",
    "PracticeCollaboratorRole",
    "PracticeCollaboratorUpdate",
    "PracticeCreate",
    "PracticeEvent",
    "PracticeEventBase",
    "PracticeEventCreate",
    "PracticeEventType",
    "PracticeEventUpdate",
    "PracticeLabel",
    "PracticePhase",
    "PracticePhaseBase",
    "PracticePhaseCreate",
    "PracticePhaseStatus",
    "PracticePhaseUpdate",
    "PracticePriority",
    "PracticeStatus",
    "PracticeUpdate",
    "Reminder",
    "ReminderBase",
    "ReminderCreate",
    "ReminderStatus",
    "ReminderUpdate",
    "RemoveLabelRequest",
    "SkipPhaseRequest",
    "UpdatePhaseRequest",
    "User",
    "UserBase",
    "UserCreate",
    "UserRole",
    "UserStatus",
    "UserUpdate",
    "VisualPosition",
]
