/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe. Usato da docker-compose, Render, e dal frontend al boot.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Session
         * @description V0 login fake. Verifica che l'utente esista e ritorna i suoi dati.
         *
         *     Il frontend salva poi `user_id` in `localStorage` e lo invia come header
         *     `X-User-Id` su tutte le successive richieste.
         */
        post: operations["create_session_api_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description V0: lista utenti studio. Filtra di default `status=attivo`.
         *
         *     Pensato per il dropdown utente del frontend (V0 demo).
         */
        get: operations["list_users_api_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Clients
         * @description Ricerca clienti per combobox del modal Nuova Pratica.
         *
         *     Match case-insensitive su code/ragione_sociale/piva/cf. Restituisce hit
         *     arricchiti con `practice_count` totale, aperte e `cliente_dal_anno`
         *     (estratto da `created_at`). Default top 10.
         */
        get: operations["search_clients_api_clients_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Clients
         * @description Lista paginata + ricerca case-insensitive.
         */
        get: operations["list_clients_api_clients_get"];
        put?: never;
        /**
         * Create Client
         * @description Crea cliente, auto-assegna `code` CL-NNNN, valida P.IVA e CF.
         */
        post: operations["create_client_api_clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Client
         * @description Scheda cliente. Logga `viewed_l1` perché tabella L1 PROTETTO.
         */
        get: operations["get_client_api_clients__client_id__get"];
        /** Update Client */
        put: operations["update_client_api_clients__client_id__put"];
        post?: never;
        /**
         * Delete Client
         * @description Soft delete cliente. 409 se ha pratiche aperte (status != chiusa/archiviata).
         *
         *     Setta `status='archiviato'` (status enum V0: attivo|sospeso|archiviato) +
         *     `deleted_at=now`. Activity log 'deleted'.
         */
        delete: operations["delete_client_api_clients__client_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{client_id}/practices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Client Practices
         * @description Lista pratiche del cliente (per scheda cliente).
         */
        get: operations["list_client_practices_api_clients__client_id__practices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Categories
         * @description Lista categorie. Default attive=True (per dropdown wizard pratica).
         */
        get: operations["list_categories_api_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Templates For Category
         * @description Lista fasi del template per la categoria, ordinate per order_index.
         */
        get: operations["list_templates_for_category_api_templates__category_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/category/{category_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Template Preview
         * @description Restituisce le fasi del template con date pianificate cumulative
         *     a partire da `apertura`, e calcola la scadenza finale.
         *
         *     Usato dal modal Nuova Pratica:
         *     - Step 2 mostra la scadenza calcolata
         *     - Step 3 mostra le N fasi con durata e anteprima date
         */
        get: operations["template_preview_api_templates_category__category_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Practices */
        get: operations["list_practices_api_practices_get"];
        put?: never;
        /**
         * Create Practice
         * @description Wizard creazione pratica: genera Practice + instanzia fasi dal template.
         *
         *     Opzionale: se `create_default_reminders=True`, crea anche un Reminder per
         *     ogni fase (days_before=2). Se `label_ids` non vuoto, aggancia le etichette.
         */
        post: operations["create_practice_api_practices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practices/{practice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Practice Detail
         * @description Detail completo con joined names — una sola GET per la pagina.
         */
        get: operations["get_practice_detail_api_practices__practice_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practices/{practice_id}/phases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Practice Phases */
        get: operations["list_practice_phases_api_practices__practice_id__phases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practices/{practice_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Practice Events */
        get: operations["list_practice_events_api_practices__practice_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practices/{practice_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Practice */
        post: operations["archive_practice_api_practices__practice_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practices/{practice_id}/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Practice Labels */
        get: operations["list_practice_labels_api_practices__practice_id__labels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/phases/{phase_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Phase
         * @description Modifica una fase. Solo se status=pending (le altre sono immutabili).
         */
        put: operations["update_phase_api_phases__phase_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/phases/{phase_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Phase
         * @description Marca la fase come `completed`. Optional: crea un reminder collegato.
         */
        post: operations["complete_phase_api_phases__phase_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/phases/{phase_id}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Skip Phase
         * @description Salta una fase con motivazione obbligatoria. Activity log con reason.
         */
        post: operations["skip_phase_api_phases__phase_id__skip_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Event
         * @description Crea un nodo-evento ad-hoc agganciato alla pratica (e opzionalmente alla fase).
         */
        post: operations["create_event_api_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Event */
        put: operations["update_event_api_events__event_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Note */
        post: operations["create_note_api_notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Note */
        put: operations["update_note_api_notes__note_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Attachments
         * @description Lista allegati (filtri arrivano in iterazione successiva).
         */
        get: operations["list_attachments_api_attachments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reminders */
        get: operations["list_reminders_api_reminders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Activity */
        get: operations["list_activity_api_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard
         * @description Aggregato KPI enriched per la home dashboard (1 sola GET = pagina pronta).
         */
        get: operations["get_dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Global Search
         * @description Ricerca multi-entità: clients (ragione_sociale, piva, code),
         *     practices (title, code), events (title). Top `limit` risultati totali.
         */
        get: operations["global_search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityEnriched
         * @description Activity log row arricchita: actor + entity_label leggibile.
         */
        ActivityEnriched: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Action
             * @enum {string}
             */
            action: "created" | "updated" | "deleted" | "completed" | "uploaded" | "commented" | "viewed_l1";
            /**
             * Entity Type
             * @enum {string}
             */
            entity_type: "practice" | "phase" | "event" | "note" | "attachment" | "client";
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Practice Id */
            practice_id?: string | null;
            actor?: components["schemas"]["UserMiniSummary"] | null;
            /** Entity Label */
            entity_label: string;
            /** Phase Name */
            phase_name?: string | null;
        };
        /** ActivityLog */
        ActivityLog: {
            /**
             * Actor Id
             * Format: uuid
             */
            actor_id: string;
            /**
             * Action
             * @enum {string}
             */
            action: "created" | "updated" | "deleted" | "completed" | "uploaded" | "commented" | "viewed_l1";
            /**
             * Entity Type
             * @enum {string}
             */
            entity_type: "practice" | "phase" | "event" | "note" | "attachment" | "client";
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Practice Id */
            practice_id?: string | null;
            /** Metadata */
            metadata?: Record<string, never> | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** Attachment */
        Attachment: {
            /**
             * Practice Id
             * Format: uuid
             */
            practice_id: string;
            /** Phase Id */
            phase_id?: string | null;
            /** Event Id */
            event_id?: string | null;
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
            /** Mime Type */
            mime_type?: string | null;
            /** Storage Key */
            storage_key: string;
            /**
             * Source
             * @default local
             * @enum {string}
             */
            source: "local" | "drive" | "db" | "scan" | "url";
            /**
             * Uploaded By
             * Format: uuid
             */
            uploaded_by: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AttachmentEnriched */
        AttachmentEnriched: {
            attachment: components["schemas"]["Attachment"];
            uploaded_by_user?: components["schemas"]["UserSummary"] | null;
        };
        /** Category */
        Category: {
            /** Name */
            name: string;
            /** Group Name */
            group_name?: string | null;
            /** Icon */
            icon?: string | null;
            /** Color */
            color?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** CategoryDistribution */
        CategoryDistribution: {
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Category Name */
            category_name: string;
            /** Count */
            count: number;
        };
        /** CategorySummary */
        CategorySummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Group Name */
            group_name?: string | null;
            /** Icon */
            icon?: string | null;
            /** Color */
            color?: string | null;
        };
        /** Client */
        Client: {
            /** Code */
            code: string;
            /**
             * Type
             * @enum {string}
             */
            type: "persona_fisica" | "societa" | "altro";
            /** Ragione Sociale */
            ragione_sociale: string;
            /** Piva */
            piva?: string | null;
            /** Cf */
            cf?: string | null;
            /** Ateco */
            ateco?: string | null;
            /** Indirizzo Sede */
            indirizzo_sede?: string | null;
            /** Email */
            email?: string | null;
            /** Pec */
            pec?: string | null;
            /** Telefono */
            telefono?: string | null;
            /** Contatto Referente */
            contatto_referente?: string | null;
            /** Note */
            note?: string | null;
            /**
             * Status
             * @default attivo
             * @enum {string}
             */
            status: "attivo" | "sospeso" | "archiviato";
            /** Created By */
            created_by?: string | null;
            /** Deleted At */
            deleted_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ClientCreate */
        ClientCreate: {
            /** Code */
            code: string;
            /**
             * Type
             * @enum {string}
             */
            type: "persona_fisica" | "societa" | "altro";
            /** Ragione Sociale */
            ragione_sociale: string;
            /** Piva */
            piva?: string | null;
            /** Cf */
            cf?: string | null;
            /** Ateco */
            ateco?: string | null;
            /** Indirizzo Sede */
            indirizzo_sede?: string | null;
            /** Email */
            email?: string | null;
            /** Pec */
            pec?: string | null;
            /** Telefono */
            telefono?: string | null;
            /** Contatto Referente */
            contatto_referente?: string | null;
            /** Note */
            note?: string | null;
            /**
             * Status
             * @default attivo
             * @enum {string}
             */
            status: "attivo" | "sospeso" | "archiviato";
            /** Created By */
            created_by?: string | null;
            /** Deleted At */
            deleted_at?: string | null;
        };
        /**
         * ClientSearchHit
         * @description Hit per combobox 'cerca cliente' del modal Nuova Pratica.
         */
        ClientSearchHit: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Ragione Sociale */
            ragione_sociale: string;
            /**
             * Type
             * @enum {string}
             */
            type: "persona_fisica" | "societa" | "altro";
            /** Piva */
            piva?: string | null;
            /** Cf */
            cf?: string | null;
            /** Indirizzo Sede */
            indirizzo_sede?: string | null;
            /** Cliente Dal Anno */
            cliente_dal_anno: number;
            /** Practice Count */
            practice_count: number;
            /** Practice Count Open */
            practice_count_open: number;
        };
        /** ClientUpdate */
        ClientUpdate: {
            /** Code */
            code?: string | null;
            /** Type */
            type?: ("persona_fisica" | "societa" | "altro") | null;
            /** Ragione Sociale */
            ragione_sociale?: string | null;
            /** Piva */
            piva?: string | null;
            /** Cf */
            cf?: string | null;
            /** Ateco */
            ateco?: string | null;
            /** Indirizzo Sede */
            indirizzo_sede?: string | null;
            /** Email */
            email?: string | null;
            /** Pec */
            pec?: string | null;
            /** Telefono */
            telefono?: string | null;
            /** Contatto Referente */
            contatto_referente?: string | null;
            /** Note */
            note?: string | null;
            /** Status */
            status?: ("attivo" | "sospeso" | "archiviato") | null;
            /** Created By */
            created_by?: string | null;
            /** Deleted At */
            deleted_at?: string | null;
        };
        /** CompletePhaseBody */
        CompletePhaseBody: {
            /** Note */
            note?: string | null;
            /** Actual End */
            actual_end?: string | null;
            /**
             * Create Reminder
             * @default false
             */
            create_reminder: boolean;
            /** Reminder Title */
            reminder_title?: string | null;
            /** Reminder Date */
            reminder_date?: string | null;
            /**
             * Reminder Days Before
             * @default 0
             */
            reminder_days_before: number;
            /** Reminder Recipient */
            reminder_recipient?: string | null;
        };
        /** CreateEventRequest */
        CreateEventRequest: {
            /**
             * Practice Id
             * Format: uuid
             */
            practice_id: string;
            /** Phase Id */
            phase_id?: string | null;
            /**
             * Event Type
             * @enum {string}
             */
            event_type: "telefonata_in" | "telefonata_out" | "email_in" | "email_out" | "incontro" | "documento_in" | "documento_out" | "delega" | "f24" | "attesa_cliente" | "nota_interna" | "esterno";
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            /** Event Time */
            event_time?: string | null;
            /**
             * Author Id
             * Format: uuid
             */
            author_id: string;
            /** Visual Position */
            visual_position?: ("top" | "bottom") | null;
        };
        /** CreatePracticeRequest */
        CreatePracticeRequest: {
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Responsible Id */
            responsible_id?: string | null;
            /**
             * Apertura
             * Format: date
             */
            apertura: string;
            /** Scadenza */
            scadenza?: string | null;
            /**
             * Priority
             * @default media
             * @enum {string}
             */
            priority: "bassa" | "media" | "alta";
            /**
             * Collaborator Ids
             * @default []
             */
            collaborator_ids: string[];
            /**
             * Label Ids
             * @default []
             */
            label_ids: string[];
            /**
             * Create Default Reminders
             * @default false
             */
            create_default_reminders: boolean;
            /**
             * Phase Overrides
             * @default []
             */
            phase_overrides: components["schemas"]["PhaseOverride"][];
        };
        /** CreatePracticeResponse */
        CreatePracticeResponse: {
            /**
             * Practice Id
             * Format: uuid
             */
            practice_id: string;
            /** Code */
            code: string;
            /** Phase Ids */
            phase_ids: string[];
        };
        /**
         * DashboardKPI
         * @description KPI aggregati per la home dashboard V0.
         */
        DashboardKPI: {
            /** Totale Pratiche */
            totale_pratiche: number;
            /** Counts Per Status */
            counts_per_status: components["schemas"]["StatusCount"][];
            /** Pratiche In Ritardo */
            pratiche_in_ritardo: number;
            /** Completate Mese */
            completate_mese: number;
            /** Scadenze Prossime 7Gg */
            scadenze_prossime_7gg: number;
            /** Top Urgenti */
            top_urgenti: components["schemas"]["TopUrgentPractice"][];
            /** Distribuzione Categorie */
            distribuzione_categorie: components["schemas"]["CategoryDistribution"][];
            /** Ultime Attivita */
            ultime_attivita: components["schemas"]["ActivityEnriched"][];
            /** Carico Per Utente */
            carico_per_utente: components["schemas"]["UserWorkload"][];
        };
        /** EventEnriched */
        EventEnriched: {
            event: components["schemas"]["PracticeEvent"];
            author?: components["schemas"]["UserSummary"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LabelSummary */
        LabelSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Color */
            color: string;
        };
        /** Note */
        Note: {
            /**
             * Practice Id
             * Format: uuid
             */
            practice_id: string;
            /** Phase Id */
            phase_id?: string | null;
            /** Event Id */
            event_id?: string | null;
            /** Content */
            content: string;
            /**
             * Author Id
             * Format: uuid
             */
            author_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** NoteCreate */
        NoteCreate: {
            /**
             * Practice Id
             * Format: uuid
             */
            practice_id: string;
            /** Phase Id */
            phase_id?: string | null;
            /** Event Id */
            event_id?: string | null;
            /** Content */
            content: string;
            /**
             * Author Id
             * Format: uuid
             */
            author_id: string;
        };
        /** NoteEnriched */
        NoteEnriched: {
            note: components["schemas"]["Note"];
            author?: components["schemas"]["UserSummary"] | null;
        };
        /** NoteUpdate */
        NoteUpdate: {
            /** Practice Id */
            practice_id?: string | null;
            /** Phase Id */
            phase_id?: string | null;
            /** Event Id */
            event_id?: string | null;
            /** Content */
            content?: string | null;
            /** Author Id */
            author_id?: string | null;
        };
        /** Page[ActivityLog] */
        Page_ActivityLog_: {
            /** Items */
            items: components["schemas"]["ActivityLog"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** Page[Client] */
        Page_Client_: {
            /** Items */
            items: components["schemas"]["Client"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** Page[Practice] */
        Page_Practice_: {
            /** Items */
            items: components["schemas"]["Practice"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /**
         * PhaseEnriched
         * @description PracticePhase + nome+avatar dell'assegnatario.
         */
        PhaseEnriched: {
            phase: components["schemas"]["PracticePhase"];
            assignee?: components["schemas"]["UserSummary"] | null;
        };
        /** PhaseOverride */
        PhaseOverride: {
            /** Order Index */
            order_index: number;
            /** Name */
            name?: string | null;
            /** Planned Start */
            planned_start?: string | null;
            /** Planned End */
            planned_end?: string | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** PhaseTemplate */
        PhaseTemplate: {
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Order Index */
            order_index: number;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Duration Days */
            duration_days?: number | null;
            /** Default Role */
            default_role?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** Practice */
        Practice: {
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /** Client Token */
            client_token: string;
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Responsible Id */
            responsible_id?: string | null;
            /**
             * Apertura
             * Format: date
             */
            apertura: string;
            /** Scadenza */
            scadenza?: string | null;
            /**
             * Priority
             * @default media
             * @enum {string}
             */
            priority: "bassa" | "media" | "alta";
            /**
             * Status
             * @enum {string}
             */
            status: "aperta" | "in_corso" | "in_attesa" | "sospesa" | "chiusa" | "archiviata";
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * PracticeDetail
         * @description Aggregato joined per la pagina Dettaglio Pratica.
         *
         *     Una sola GET ritorna tutto quello che serve a Daisy/Kowy per renderare
         *     header + tab bar + vista albero + drawer: zero lookup extra lato frontend.
         */
        PracticeDetail: {
            practice: components["schemas"]["Practice"];
            client?: components["schemas"]["Client"] | null;
            category?: components["schemas"]["CategorySummary"] | null;
            responsible?: components["schemas"]["UserSummary"] | null;
            /** Labels */
            labels: components["schemas"]["LabelSummary"][];
            /** Phases */
            phases: components["schemas"]["PhaseEnriched"][];
            /** Events */
            events: components["schemas"]["EventEnriched"][];
            /** Notes */
            notes: components["schemas"]["NoteEnriched"][];
            /** Attachments */
            attachments: components["schemas"]["AttachmentEnriched"][];
            /** Collaborators */
            collaborators: components["schemas"]["UserSummary"][];
            /** Progress Pct */
            progress_pct: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
        };
        /** PracticeEvent */
        PracticeEvent: {
            /**
             * Practice Id
             * Format: uuid
             */
            practice_id: string;
            /** Phase Id */
            phase_id?: string | null;
            /**
             * Event Type
             * @enum {string}
             */
            event_type: "telefonata_in" | "telefonata_out" | "email_in" | "email_out" | "incontro" | "documento_in" | "documento_out" | "delega" | "f24" | "attesa_cliente" | "nota_interna" | "esterno";
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            /** Event Time */
            event_time?: string | null;
            /**
             * Author Id
             * Format: uuid
             */
            author_id: string;
            /** Visual Position */
            visual_position?: ("top" | "bottom") | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PracticeEventUpdate */
        PracticeEventUpdate: {
            /** Practice Id */
            practice_id?: string | null;
            /** Phase Id */
            phase_id?: string | null;
            /** Event Type */
            event_type?: ("telefonata_in" | "telefonata_out" | "email_in" | "email_out" | "incontro" | "documento_in" | "documento_out" | "delega" | "f24" | "attesa_cliente" | "nota_interna" | "esterno") | null;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Event Date */
            event_date?: string | null;
            /** Event Time */
            event_time?: string | null;
            /** Author Id */
            author_id?: string | null;
            /** Visual Position */
            visual_position?: ("top" | "bottom") | null;
        };
        /** PracticePhase */
        PracticePhase: {
            /**
             * Practice Id
             * Format: uuid
             */
            practice_id: string;
            /** Template Id */
            template_id?: string | null;
            /** Order Index */
            order_index: number;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Assignee Id */
            assignee_id?: string | null;
            /** Planned Start */
            planned_start?: string | null;
            /** Planned End */
            planned_end?: string | null;
            /** Actual Start */
            actual_start?: string | null;
            /** Actual End */
            actual_end?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "in_progress" | "completed" | "skipped" | "blocked";
            /** Skip Reason */
            skip_reason?: string | null;
            /** Completed By */
            completed_by?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** Reminder */
        Reminder: {
            /**
             * Practice Id
             * Format: uuid
             */
            practice_id: string;
            /** Phase Id */
            phase_id?: string | null;
            /** Title */
            title: string;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /**
             * Days Before
             * @default 0
             */
            days_before: number;
            /**
             * Recipient Id
             * Format: uuid
             */
            recipient_id: string;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "sent" | "dismissed";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SearchHit */
        SearchHit: {
            /**
             * Type
             * @enum {string}
             */
            type: "client" | "practice" | "event";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /** Url */
            url: string;
            /** Sublabel */
            sublabel?: string | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Hits */
            hits: components["schemas"]["SearchHit"][];
            /** Total */
            total: number;
        };
        /** SessionRequest */
        SessionRequest: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** SessionResponse */
        SessionResponse: {
            user: components["schemas"]["User"];
        };
        /** SkipPhaseBody */
        SkipPhaseBody: {
            /** Skip Reason */
            skip_reason: string;
        };
        /** StatusCount */
        StatusCount: {
            /**
             * Status
             * @enum {string}
             */
            status: "aperta" | "in_corso" | "in_attesa" | "sospesa" | "chiusa" | "archiviata";
            /** Count */
            count: number;
        };
        /** TemplatePhasePreview */
        TemplatePhasePreview: {
            /** Order Index */
            order_index: number;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Duration Days */
            duration_days: number;
            /**
             * Planned Start
             * Format: date
             */
            planned_start: string;
            /**
             * Planned End
             * Format: date
             */
            planned_end: string;
        };
        /**
         * TemplatePreview
         * @description Anteprima fasi + scadenza calcolata, per modal Nuova Pratica step 2/3.
         */
        TemplatePreview: {
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Category Name */
            category_name: string;
            /**
             * Apertura
             * Format: date
             */
            apertura: string;
            /**
             * Scadenza Calcolata
             * Format: date
             */
            scadenza_calcolata: string;
            /**
             * Total Duration Days
             * @description Somma di duration_days delle fasi (giorni cumulativi).
             */
            total_duration_days: number;
            /** Phases */
            phases: components["schemas"]["TemplatePhasePreview"][];
        };
        /** TopUrgentPractice */
        TopUrgentPractice: {
            /**
             * Practice Id
             * Format: uuid
             */
            practice_id: string;
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Priority */
            priority: string;
            /**
             * Status
             * @enum {string}
             */
            status: "aperta" | "in_corso" | "in_attesa" | "sospesa" | "chiusa" | "archiviata";
            /** Scadenza */
            scadenza: string | null;
            /** Giorni Al Target */
            giorni_al_target: number | null;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /** Client Ragione Sociale */
            client_ragione_sociale?: string | null;
            responsible?: components["schemas"]["UserMiniSummary"] | null;
        };
        /** UpdatePhaseRequest */
        UpdatePhaseRequest: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Assignee Id */
            assignee_id?: string | null;
            /** Planned Start */
            planned_start?: string | null;
            /** Planned End */
            planned_end?: string | null;
        };
        /** User */
        User: {
            /** Email */
            email: string;
            /** Nome */
            nome: string;
            /** Cognome */
            cognome: string;
            /**
             * Role
             * @enum {string}
             */
            role: "titolare" | "senior" | "junior" | "esterno";
            /**
             * Status
             * @default attivo
             * @enum {string}
             */
            status: "attivo" | "sospeso" | "disattivo";
            /** Avatar Color */
            avatar_color?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Access At */
            last_access_at?: string | null;
        };
        /** UserMiniSummary */
        UserMiniSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nome */
            nome: string;
            /** Cognome */
            cognome: string;
            /** Role */
            role: string;
            /** Role Label */
            role_label: string;
            /** Initials */
            initials: string;
            /** Avatar Color */
            avatar_color?: string | null;
        };
        /**
         * UserSummary
         * @description Estratto di User per evitare di esporre PII non necessaria (no email).
         */
        UserSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nome */
            nome: string;
            /** Cognome */
            cognome: string;
            /** Role */
            role: string;
            /** Initials */
            initials: string;
            /** Avatar Color */
            avatar_color?: string | null;
        };
        /** UserWorkload */
        UserWorkload: {
            user: components["schemas"]["UserMiniSummary"];
            /** Pratiche Aperte */
            pratiche_aperte: number;
            /** Pratiche In Ritardo */
            pratiche_in_ritardo: number;
            /** Load Pct */
            load_pct: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_session_api_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: {
                status?: ("attivo" | "sospeso" | "disattivo") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_clients_api_clients_search_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientSearchHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clients_api_clients_get: {
        parameters: {
            query?: {
                /** @description Ricerca su code, ragione_sociale, piva, cf, email */
                q?: string | null;
                type?: ("persona_fisica" | "societa" | "altro") | null;
                status?: ("attivo" | "sospeso" | "archiviato") | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Client_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_client_api_clients_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_api_clients__client_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_client_api_clients__client_id__put: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_client_api_clients__client_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_client_practices_api_clients__client_id__practices_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Practice"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_categories_get: {
        parameters: {
            query?: {
                active?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_for_category_api_templates__category_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhaseTemplate"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    template_preview_api_templates_category__category_id__preview_get: {
        parameters: {
            query?: {
                /** @description Data apertura ipotetica (default oggi) */
                apertura?: string | null;
            };
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplatePreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_practices_api_practices_get: {
        parameters: {
            query?: {
                /** @description Ricerca su title, code */
                q?: string | null;
                status?: ("aperta" | "in_corso" | "in_attesa" | "sospesa" | "chiusa" | "archiviata") | null;
                priority?: ("bassa" | "media" | "alta") | null;
                responsible_id?: string | null;
                client_id?: string | null;
                category_id?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Practice_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_practice_api_practices_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePracticeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePracticeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_practice_detail_api_practices__practice_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path: {
                practice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_practice_phases_api_practices__practice_id__phases_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                practice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticePhase"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_practice_events_api_practices__practice_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                practice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_practice_api_practices__practice_id__archive_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path: {
                practice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Practice"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_practice_labels_api_practices__practice_id__labels_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                practice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_phase_api_phases__phase_id__put: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path: {
                phase_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePhaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticePhase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_phase_api_phases__phase_id__complete_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path: {
                phase_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompletePhaseBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticePhase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skip_phase_api_phases__phase_id__skip_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path: {
                phase_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkipPhaseBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticePhase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_event_api_events_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_event_api_events__event_id__put: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PracticeEventUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_note_api_notes_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_note_api_notes__note_id__put: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path: {
                note_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_attachments_api_attachments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"][];
                };
            };
        };
    };
    list_reminders_api_reminders_get: {
        parameters: {
            query?: {
                status?: ("pending" | "sent" | "dismissed") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reminder"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_activity_api_activity_get: {
        parameters: {
            query?: {
                actor_id?: string | null;
                action?: ("created" | "updated" | "deleted" | "completed" | "uploaded" | "commented" | "viewed_l1") | null;
                entity_type?: ("practice" | "phase" | "event" | "note" | "attachment" | "client") | null;
                practice_id?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ActivityLog_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardKPI"];
                };
            };
        };
    };
    global_search_api_search_get: {
        parameters: {
            query: {
                /** @description Stringa di ricerca (min 2 char) */
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
